// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsPHQq7zcM4uZXarFDz868zgAg2UOOQGM',
    appId: '1:237297933602:web:1fe0acb576bc9ed874997b',
    messagingSenderId: '237297933602',
    projectId: 'initflutter',
    authDomain: 'initflutter.firebaseapp.com',
    storageBucket: 'initflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAU5LK-3JOLaJdp5AQ1deo3qC71RoE8fk',
    appId: '1:237297933602:android:869a2adb215cf4cd74997b',
    messagingSenderId: '237297933602',
    projectId: 'initflutter',
    storageBucket: 'initflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA373VvPLsV5rCdgoxqF_1RJ9CFGwYBqaY',
    appId: '1:237297933602:ios:cb521abd1b61657a74997b',
    messagingSenderId: '237297933602',
    projectId: 'initflutter',
    storageBucket: 'initflutter.appspot.com',
    iosClientId: '237297933602-95r0aa9coo9aa2vshe9c5bap7rlmkiot.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstbd233',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA373VvPLsV5rCdgoxqF_1RJ9CFGwYBqaY',
    appId: '1:237297933602:ios:d64b50cf1be9004e74997b',
    messagingSenderId: '237297933602',
    projectId: 'initflutter',
    storageBucket: 'initflutter.appspot.com',
    iosClientId: '237297933602-824kdhgoib72v30rojsiri58f8nmo197.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstbd233.RunnerTests',
  );
}
